### ISSUE TITLE
Element not found bug when using PhantomJS?

### ISSUE THREAD

**Issue by dnkmiller** [patrickherrmann/Bumblebee#33]
Not quite sure why this is happening. If I have the code:
    
    Session
        .NavigateTo<LogonPage>(Resources.BaseUrl)
        .Username.EnterText(Users.AdminUser.Username)
        .Password.EnterText(Users.AdminUser.Password)
        .LogonButton.Click<HomePage>()
        .MyDetailsLink.Click();

I get an 'Element(s) NOT Found: GAVE UP' timeout from the WebElementLocator on the MyDetailsLink element.

If I add a ScopeTo line like so:

    Session
        .NavigateTo<LogonPage>(Resources.BaseUrl)
        .Username.EnterText(Users.AdminUser.Username)
        .Password.EnterText(Users.AdminUser.Password)
        .LogonButton.Click<HomePage>()
        .ScopeTo<HomePage>
        .MyDetailsLink.Click();

Then everything works as expected. Note that this only seems to happen using PhantomJS - Chrome is fine. If I replace the ScopeTo with a Pause, I still get the error described above.

**Comment by toddmeinershagen** [comment]
Hi,

 

I can’t tell from your code how the HomePage is instantiated, but my guess is that the HomePage class constructor needs to add a check for the MyDetailsLink on construction.  The WebBlock base class that we provide has a Wait property that you can leverage in this case.  You could also put this wait (which returns an element) in your MyDetailsLink property.

 

Example:  (gist is here <https://gist.github.com/toddmeinershagen/ad5f8e61624418eac537> )

 

public class HomePage : WebBlock

{

  public HomePage(Session session)

    : base(Session)

  {

    Wait.Until(driver => driver.GetElement(By.TagName("myDetailsLink")));

  }

}

 

Hope this helps,

 

 

Todd

**Comment by toddmeinershagen** [comment]
DId my suggestion to put logic in the constructor to wait for the details link resolve your issue with Phantom?

**Comment by dnkmiller** [comment]
Yes. All resolved now - thanks for the help.
